[package]
name = "balloons"
version = "0.0.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"

[dependencies]
property = "~0.2"

[badges]
travis-ci = { repository = "yangby-cryptape/rust-balloons" }
